<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net48;net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>MediaEmbedKit.Mpv.WinForms</AssemblyName>
    <RootNamespace>MediaEmbedKit.Mpv.WinForms</RootNamespace>
    <Description>WinForms control for libmpv.</Description>
    <PackageId>MediaEmbedKit.Mpv.WinForms</PackageId>
    <Title>MediaEmbedKit.Mpv.WinForms</Title>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaEmbedKit.Mpv\MediaEmbedKit.Mpv.csproj" />
  </ItemGroup>
</Project>
